parameters:
#    s2n_show.example.class: S2n\ShowBundle\Example

services:
#    s2n_show.example:
#        class: %s2n_show.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
  sonata.admin.user:
    class: Listreat\MainBundle\Admin\UserAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "User", label: "Users" }
    arguments: [ null, Listreat\UserBundle\Entity\User, SonataAdminBundle:CRUD ]
    calls:
      - [ setTranslationDomain, [ ListreatMainBundle ] ]
      
  sonata.admin.shop:
    class: Listreat\MainBundle\Admin\ShopAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Shop", label: "Shops" }
    arguments: [ null, Listreat\MainBundle\Entity\Shop, SonataAdminBundle:CRUD ]
    calls:
      - [ setTranslationDomain, [ ListreatMainBundle ] ]

  sonata.admin.item:
    class: Listreat\MainBundle\Admin\ItemAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Item", label: "Items" }
    arguments: [ null, Listreat\MainBundle\Entity\Item, SonataAdminBundle:CRUD ]
    calls:
      - [ setTranslationDomain, [ ListreatMainBundle ] ]