<?php

namespace Listreat\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FollowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowRepository extends EntityRepository
{
    public function getFollowedShops($user)
    {
        $query = $this->getEntityManager()->createQuery(
              'SELECT f, s FROM ListreatMainBundle:Follow f INNER JOIN f.shop s WHERE f.user = :user ORDER BY s.id DESC'
              )->setParameter('user', $user->getId());
        return $query->getResult();
    }
}
