<?php

namespace Listreat\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopRepository extends EntityRepository
{
    public function getShopsWithEvents($limit = 10)
    {
      return $this->getEntityManager()->createQuery(
              'SELECT s, i FROM ListreatMainBundle:Shop s INNER JOIN s.items i ORDER BY i.id DESC'
              )->setMaxResults($limit)->execute();
    }
}
